Traceback (most recent call last):
  File "/Users/colbrydi/REPOS/MTH314_Textbook/envs/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/colbrydi/REPOS/MTH314_Textbook/envs/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/colbrydi/REPOS/MTH314_Textbook/envs/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/colbrydi/REPOS/MTH314_Textbook/envs/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/colbrydi/REPOS/MTH314_Textbook/envs/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/colbrydi/REPOS/MTH314_Textbook/envs/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/colbrydi/REPOS/MTH314_Textbook/envs/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/colbrydi/REPOS/MTH314_Textbook/envs/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#Compute matrix multiply using your function
x = multiply(matrix1, matrix2)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-6-469274bbe4ab>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m#Compute matrix multiply using your function[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mx[0m [0;34m=[0m [0mmultiply[0m[0;34m([0m[0mmatrix1[0m[0;34m,[0m [0mmatrix2[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m<ipython-input-2-2e7c4cda342b>[0m in [0;36mmultiply[0;34m(m1, m2)[0m
[1;32m     12[0m     [0;31m#### put your matrix multiply code here #####[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m     13[0m [0;34m[0m[0m
[0;32m---> 14[0;31m     [0;32mreturn[0m [0mresult[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'result' is not defined
NameError: name 'result' is not defined

