Traceback (most recent call last):
  File "/Users/colbrydi/REPOS/MTH314_Textbook/envs/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/colbrydi/REPOS/MTH314_Textbook/envs/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/colbrydi/REPOS/MTH314_Textbook/envs/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/colbrydi/REPOS/MTH314_Textbook/envs/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/colbrydi/REPOS/MTH314_Textbook/envs/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/colbrydi/REPOS/MTH314_Textbook/envs/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/colbrydi/REPOS/MTH314_Textbook/envs/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/colbrydi/REPOS/MTH314_Textbook/envs/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
## Modify the following code

est_log_distances = (c[0] + c[1]*np.matrix(ind)).tolist()[0]
plt.plot(ind,est_log_distances)

plt.scatter(ind,log_distances)
plt.xticks(ind,planets)
plt.ylabel('Distance (log(AU))')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-7-7fe2bbc8b401>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m## Modify the following code[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;34m[0m[0m
[0;32m----> 3[0;31m [0mest_log_distances[0m [0;34m=[0m [0;34m([0m[0mc[0m[0;34m[[0m[0;36m0[0m[0;34m][0m [0;34m+[0m [0mc[0m[0;34m[[0m[0;36m1[0m[0;34m][0m[0;34m*[0m[0mnp[0m[0;34m.[0m[0mmatrix[0m[0;34m([0m[0mind[0m[0;34m)[0m[0;34m)[0m[0;34m.[0m[0mtolist[0m[0;34m([0m[0;34m)[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0mplt[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mind[0m[0;34m,[0m[0mest_log_distances[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;34m[0m[0m

[0;31mNameError[0m: name 'c' is not defined
NameError: name 'c' is not defined

